plugins: 
    - {name: inflation_map,    type: "costmap_2d::InflationLayer"}
    - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
footprint: [[0.3, 0.2], [0.3, -0.2], [-0.3, -0.2], [-0.3, 0.2]]
inflation_radius : 0.55
cost_scaling_factor : 10
origin_x: 0
origin_y: 0
height: 5
update_frequency: 30 
publish_frequency: 20 
rolling_window: true
robot_base_frame: base_link
observation_sources : base_scan
global_frame: base_link
base_scan : 
   data_type: LaserScan
   topic: laser_scan
   sensor_frame: base_laser_link
   clearing: true
   marking: true
   expected_update_rate: 0.7
   min_obstacle_height: 0.1
   max_obstacle_height: 2